language: c
before_script:
    - brew update
    - brew install bazel
    - sudo easy_install pip
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade pycrypto pillow
script: bazel test cauliflowervest:all_smoke_tests
sudo: required
osx_image: xcode7.3
os:
  - osx

