language: c
before_script:
    - brew update
    - brew tap bazelbuild/tap
    - brew tap-pin bazelbuild/tap
    - brew install bazel
script: bazel test --test_output=all cauliflowervest:all_smoke_tests
sudo: required
osx_image: xcode9.3
os:
  - osx

